version: "3"
services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo0
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "27100:8081"
    restart: always
    networks:
      - int-dev-net

  mongo0:
    image: mongo:latest
    container_name: mongo0
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    links:
      - "mongo1:mongo1"
      - "mongo2:mongo2"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_NON_ROOT_USERNAME=user
      - MONGO_NON_ROOT_PASSWORD=user
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo/mongo-data-0:/data/db
      - ./volumes/mongo/mongo-db-config-0:/data/configdb
      - ./entrypoint/mongodb-entrypoint/master/init-mongo-master.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    networks:
      - int-dev-net

  mongo1:
    image: mongo:latest
    container_name: mongo1
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_NON_ROOT_USERNAME=user
      - MONGO_NON_ROOT_PASSWORD=user
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo/mongo-data-1:/data/db
      - ./volumes/mongo/mongo-db-config-1:/data/configdb
      - ./entrypoint/mongodb-entrypoint/slave/init-mongo-slave.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    networks:
      - int-dev-net

  mongo2:
    image: mongo:latest
    container_name: mongo2
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_NON_ROOT_USERNAME=user
      - MONGO_NON_ROOT_PASSWORD=user
    expose:
      - "27017"
    ports:
      - "27019:27017"
    volumes:
      - ./volumes/mongo/mongo-data-2:/data/db
      - ./volumes/mongo/mongo-db-config-2:/data/configdb
      - ./entrypoint/mongodb-entrypoint/slave/init-mongo-slave.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    networks:
      - int-dev-net

networks:
  int-dev-net:
    driver: bridge
