version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    expose:
      - "5432"
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - int-dev-net

networks:
  int-dev-net:
    driver: bridge
