version: '3'
services:
  event-service:
    image: xcodeassociated/elp-event-service:0.0.1
    depends_on:
      - "logstash"
      - "influxdb"
      - "keycloak"
      - "dev-kafka-zookeeper"
      - "dev-kafka-broker-1"
      - "mongo0"
      - "mongo1"
      - "mongo2"
      - "redis"
      - "eureka-service"
    external_links:
      - "eureka-service:eureka-service"
      - "influxdb:influxdb"
      - "logstash:logstash"
      - "keycloak:keycloak"
      - "dev-kafka-zookeeper:dev-kafka-zookeeper"
      - "dev-kafka-broker-1:dev-kafka-broker-1"
      - "mongo0:mongo0"
      - "mongo1:mongo1"
      - "mongo2:mongo2"
      - "redis:redis"
    build:
      context: ./services/event_service
      dockerfile: Dockerfile-build
    expose:
      - "8083"
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f","http://event-service:8083/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always
    environment:
      - WAIT_HOSTS=eureka-service:8761/actuator/health
    networks:
      - int-dev-net

networks:
  int-dev-net:
      driver: bridge
