version: '3'
services:
  web-service:
    image: xcodeassociated/elp-web-service:0.0.1
    depends_on:
      - "user-service"
      - "event-service"
      - "keycloak"
    build:
      context: ./services/web-service
      dockerfile: Dockerfile
    expose:
      - "3000"
      - "8090"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - int-dev-net

networks:
  int-dev-net:
    driver: bridge
