apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-kafka-zookeeper
  template:
    metadata:
      labels:
        app: dev-kafka-zookeeper
        tier: backend
    spec:
      containers:
        - name: dev-kafka-zookeeper
          image: wurstmeister/zookeeper
          imagePullPolicy: Always
          ports:
            - name: zookeeper
              containerPort: 2181
          volumeMounts:
            - mountPath: /data
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: zookeeper-storage-pvc
