apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
        tier: backend
    spec:
      containers:
        - name: eureka
          image: xcodeassociated/eureka-service:0.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8761
