version: "3"
services:
  keycloak:
    image: xcodeassociated/elp-keycloak:0.0.1
    environment:
      DB_ADDR: elp-db-postgres-0.c774s9paxcql.eu-central-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
    ports:
      - 9090:8080
    expose:
      - "9090"
    networks:
      - int-dev-net
networks:
  int-dev-net:
    driver: bridge
