apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        tier: backend
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: keycloak-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_PASSWORD
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_PASSWORD
          ports:
            - name: keycloak
              containerPort: 8080
