# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak
# spec:
#   ports:
#     - port: 9090
#   selector:
#     app: keycloak

apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
