apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
        tier: backend
    spec:
      containers:
        - name: postgres-keycloak
          image: postgres:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-keycloak-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-keycloak-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-keycloak-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: db-keycloak
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: postgres-keycloak-storage-pvc
