apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: backend
    spec:
      containers:
        - name: elasticsearch
          image: xcodeassociated/elasticsearch:0.0.1
          imagePullPolicy: Always
          ports:
            - name: elasticsearch-0
              containerPort: 9200
            - name: elasticsearch-1
              containerPort: 9300
          volumeMounts:
            - mountPath: /var/lib/elasticsearch
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: elasticsearch-storage-pvc
