kind: PersistentVolume
apiVersion: v1
metadata:
  name: kibana-entry-pv
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/hamashy/code/CloudNativeEventLocator/elk/kibana/config"
    type: DirectoryOrCreate
