kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-storage-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-entry-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  volumeName: logstash-entry-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
     storage: 1Gi
