kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-master-entry-pv
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/hamashy/code/CloudNativeEventLocator/entrypoint/mongodb-entrypoint/master"
    type: DirectoryOrCreate

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-slave-entry-pv
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/hamashy/code/CloudNativeEventLocator/entrypoint/mongodb-entrypoint/slave"
    type: DirectoryOrCreate
