apiVersion: v1
kind: Service
metadata:
  name: mongo0
spec:
  ports:
    - port: 27017
  selector:
    app: mongo0

---

apiVersion: v1
kind: Service
metadata:
  name: mongo1
spec:
  ports:
    - port: 27018
  selector:
    app: mongo1

---

apiVersion: v1
kind: Service
metadata:
  name: mongo2
spec:
  ports:
    - port: 27019
  selector:
    app: mongo2
