kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-storage-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 2Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-entry-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  volumeName: postgres-entry-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
     storage: 2Gi
