kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-entry-pv
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/hamashy/code/CloudNativeEventLocator/entrypoint/postgres-entrypoint"
    type: DirectoryOrCreate
