kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-entry-pvc
  labels:
    type: local
spec:
  storageClassName: standard
  volumeName: grafana-entry-pv
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
     storage: 1Gi
