apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "c2VydmljZQ=="
  EXTERNAL_TOKEN_PASSWORD: "NjJjODlkMTdkYTE2"
  KEYCLOAK_REALM-KEY: "TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFocXpKbHZ4RUJzN1J4MEdEZXBLK29pYnlYbVoyeG9BL2c2alo0OXI4eFJCSksvemNqNlZRZTZHRG81dDdoa1drVW1FeDJxbEZFcXYydTl0My81TndTeElIQVloRHYyMjFBck5rQXMvTWM5N0RZajEwN0JyMHZRd1hPSXExWjdwV0IyRENUMlM2alhrVEgvOW1kbW9NSVpNck83SW82UVVGWmlKNXNDVlJVb2hTNDUyeEdLMmdEOUl2MnZ4bFY0dlZiSXhMajJqQ1FlTis0OVpTbGM0ZUkzUm1hWFFDb0VSTnZTeGx4VzBvYlIrUEZ2cS8vNWZwdlNDSHRocVlKSVRlMDlNMktNK3c2c0ljd0gzNng0Q0kzRWZncU0zeGdJWkozODNrRlBlNnh6RHBpZzRudFduUEtSNGhFZTJoRUNBYTk4MFgvdU5XczNvbTg2NHNpNnMxWXdJREFRQUI="
