version: '3'
services:
  keycloak:
    image: xcodeassociated/elp-keycloak:0.0.1
    environment:
      DB_ADDR: elp-db-postgres-0.c774s9paxcql.eu-central-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak-2
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 62c89d17da16
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_KAFKA_TOPIC_EVENTS: keycloak_event
      KEYCLOAK_KAFKA_TOPIC_ADMIN: keycloak_admin
      KEYCLOAK_KAFKA_CLIENTID: keycloak
      KEYCLOAK_KAFKA_BOOTSTRAPSERVER: PLAINTEXT://dev-kafka-broker-1:9092
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
    ports:
      - 9090:8080
    expose:
      - "9090"
    networks:
      - int-dev-net

  dev-kafka-zookeeper:
    container_name: dev-kafka-zookeeper
    hostname: dev-kafka-zookeeper
    restart: unless-stopped
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
    volumes:
      - ./volumes/dev-kafka-zookeeper-data:/data
    networks:
      - int-dev-net

  dev-kafka-broker-1:
    container_name: dev-kafka-broker-1
    hostname: dev-kafka-broker-1
    restart: unless-stopped
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: dev-kafka-broker-1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: dev-kafka-zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "dev_sample_topic:1:1:compact"
      ## note: AWS memory limit
      KAFKA_HEAP_OPTS: "-Xmx512M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/dev-kafka-data:/kafka
    networks:
      - int-dev-net

  mongodb-cluster:
    image: mongo:latest
    container_name: mongodb-cluster
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_NON_ROOT_USERNAME=user
      - MONGO_NON_ROOT_PASSWORD=user
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo/mongo-data-0:/data/db
      - ./volumes/mongo/mongo-db-config-0:/data/configdb
      - ./entrypoint/mongodb-entrypoint/single/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    networks:
      - int-dev-net

  eureka-service:
    image: xcodeassociated/eureka-service:0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f","http://eureka-service:8761/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - int-dev-net

  event-service:
    image: xcodeassociated/event-service:0.0.1
    depends_on:
      - "keycloak"
      - "dev-kafka-zookeeper"
      - "dev-kafka-broker-1"
      - "mongodb-cluster"
      - "eureka-service"
    external_links:
      - "eureka-service:eureka-service"
      - "keycloak:keycloak"
      - "dev-kafka-zookeeper:dev-kafka-zookeeper"
      - "dev-kafka-broker-1:dev-kafka-broker-1"
      - "mongodb-cluster:mongodb-cluster"
    expose:
      - "8083"
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f","http://event-service:8083/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always
    environment:
      WAIT_HOSTS: "eureka-service:8761/actuator/health"
      SPRING_DATA_MONGODB_HOST: "mongodb-cluster"
      SPRING_DATA_MONGODB_USERNAME: "user"
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: "test"
      KEYCLOAK_AUTH-SERVER-URL: "https://cnf.sh/auth"
      KEYCLOAK_REALM: "service"
      KEYCLOAK_RESOURCE: "service"
      EXTERNAL_KEYCLOAK_API_URL: "https://cnf.sh/auth"
      EXTERNAL_TOKEN_API_URL: "https://cnf.sh/auth/realms/service/protocol/openid-connect/"
      EXTERNAL_TOKEN_USERNAME: "admin@admin.com"
      EXTERNAL_TOKEN_CLIENTID: "service"
      EXTERNAL_TOKEN_GRANTTYPE: "password"
      EXTERNAL_SERVICE_API_URL: "https://api.cnf.sh/user/api/"
      # SPRINGDOC_SWAGGER-UI_CONFIG-URL: "" #"/event/configuration"
      SPRINGDOC_SWAGGER-UI_PATH: "/swagger-ui.html"
      # SPRINGDOC_WEBJARS_PREFIX: "" #"/event/webjars"
      # SPRINGDOC_API-DOCS_PATH: "" #"/event/v3/api-docs"
      KAFKA_CONSUMER_TOPIC: "dev_sample_topic_b"
      KAFKA_PRODUCER_TOPIC: "dev_sample_topic_a"
      KAFKA_BOOTSTRAP-SERVERS: "http://dev-kafka-broker-1:9092"
      KAFKA_CONSUMER-GROUP-ID: "dev-event-customer-group"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka"
      KEYCLOAK_REALM-KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgMeonZv2Y0s4HPF4ksZEW9oW8G552MoRWzQLH6wnsIZwwqzeGESjVu8+fP34LtwRzEt2dXejKBf6mxPK/JOIjFAlNvkOuOYslalDFRPhV3P6BwcD0aojA5wejzyXRVFUvD8wRxI7XXjgQw+bj/TA7kw9LPNXMrMMLtiPuXu/Ldb02g5DYpXereYxlVQU/14WBSeUFkpKvy9nPEp+M5tuB4n+0QO87tqqcCfVmryaTe2ypd2io6/rkqGz+AJC3KZ4xPYBmt+pojt13P1PmI/WnjvyxE16vIwexqg0DP9H714fbzBEST5STRsWhkYLssd78bMvyp1aLwqiTmR6Mzh8dQIDAQAB"
      ## secrets:
      SPRING_DATA_MONGODB_PASSWORD: "user"
      EXTERNAL_TOKEN_PASSWORD: "62c89d17da16"
    networks:
      - int-dev-net

  user-service:
    image: xcodeassociated/user-service:0.0.1
    depends_on:
      - "eureka-service"
      - "keycloak"
      - "dev-kafka-zookeeper"
      - "dev-kafka-broker-1"
    external_links:
      - "eureka-service:eureka-service"
      - "keycloak:keycloak"
      - "dev-kafka-zookeeper:dev-kafka-zookeeper"
      - "dev-kafka-broker-1:dev-kafka-broker-1"
    expose:
      - "8082"
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f","http://user-service:8082/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 10
    restart: always
    environment:
      WAIT_HOSTS: "eureka-service:8761/actuator/health"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://elp-db-postgres-0.c774s9paxcql.eu-central-1.rds.amazonaws.com:5432/service"
      SPRING_DATASOURCE_USERNAME: "service"
      KEYCLOAK_AUTH-SERVER-URL: "https://cnf.sh/auth"
      KEYCLOAK_REALM: "service"
      KEYCLOAK_RESOURCE: "service"
      EXTERNAL_KEYCLOAK_API_URL: "https://cnf.sh/auth/"
      EXTERNAL_TOKEN_API_URL: "https://cnf.sh/auth/realms/service/protocol/openid-connect/"
      EXTERNAL_TOKEN_USERNAME: "admin@admin.com"
      EXTERNAL_TOKEN_CLIENTID: "service"
      EXTERNAL_TOKEN_GRANTTYPE: "password"
      EXTERNAL_SERVICE_API_URL: "http://event-service:8083/event/api/"
      SPRINGDOC_SWAGGER-UI_PATH: "/swagger-ui.html"
      KAFKA_CONSUMER_TOPIC: "dev_sample_topic_a"
      KAFKA_PRODUCER_TOPIC: "dev_sample_topic_b"
      KAFKA_BOOTSTRAP-SERVERS: "http://dev-kafka-broker-1:9092"
      KAFKA_CONSUMER-GROUP-ID: "dev-sample-customer-group"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka"
      KAFKA_KEYCLOAK_EVENT_TOPIC: "keycloak_event"
      KAFKA_KEYCLOAK_ADMIN_TOPIC: "keycloak_admin"
      ## secrets:
      SPRING_DATASOURCE_PASSWORD: "service"
      KEYCLOAK_REALM-KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgMeonZv2Y0s4HPF4ksZEW9oW8G552MoRWzQLH6wnsIZwwqzeGESjVu8+fP34LtwRzEt2dXejKBf6mxPK/JOIjFAlNvkOuOYslalDFRPhV3P6BwcD0aojA5wejzyXRVFUvD8wRxI7XXjgQw+bj/TA7kw9LPNXMrMMLtiPuXu/Ldb02g5DYpXereYxlVQU/14WBSeUFkpKvy9nPEp+M5tuB4n+0QO87tqqcCfVmryaTe2ypd2io6/rkqGz+AJC3KZ4xPYBmt+pojt13P1PmI/WnjvyxE16vIwexqg0DP9H714fbzBEST5STRsWhkYLssd78bMvyp1aLwqiTmR6Mzh8dQIDAQAB"
      EXTERNAL_TOKEN_PASSWORD: "62c89d17da16"
    networks:
      - int-dev-net

  web-service:
    image: xcodeassociated/web-service:0.0.1-dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - int-dev-net

networks:
  int-dev-net:
      driver: bridge
